import puppeteer from 'puppeteer';
const b = await puppeteer.launch({headless:'new',args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const p = await b.newPage();
const errs=[], notable=[];
p.on('pageerror', e=>errs.push(e.message));
p.on('console', m=>{ const t=m.text();
  if (m.type()==='error') errs.push(t);
  if (/dungeon|Dungeon|feature|flag/i.test(t)) notable.push(`[${m.type()}] ${t}`); });
p.on('response', r=>{ if(r.status()>=400 && !/favicon/.test(r.url())) errs.push(`HTTP ${r.status()} ${r.url().replace(/^https?:\/\/[^/]+/,'')}`); });
await p.goto('http://localhost:5173/play/?dungeon=1',{waitUntil:'domcontentloaded',timeout:60000});
await new Promise(r=>setTimeout(r,15000));
const flag = await p.evaluate(()=>({ flag: window.__features?.get?.('dungeon'), stored: localStorage.getItem('ec_feature_flags') }));
console.log('  dungeon flag enabled:', flag.flag, '| localStorage:', flag.stored);
const hasCard = await p.evaluate(()=>/dungeon/i.test(document.body.innerText));
console.log('  "dungeon" appears in page text:', hasCard);
console.log('  notable logs:'); notable.slice(0,6).forEach(l=>console.log('    '+l));
console.log('  errors:', errs.length); errs.slice(0,6).forEach(e=>console.log('    '+e.slice(0,150)));
await p.screenshot({path:'/tmp/dungeon.png'});
await b.close();
