import puppeteer from 'puppeteer';
const b=await puppeteer.launch({headless:'new',args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const p=await b.newPage(); await p.setViewport({width:1280,height:800});
const errs=[];
p.on('pageerror',e=>errs.push(e.message));
p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
await p.goto('http://localhost:5173/dungeon-preview.html?roomType=combat&seed=4242&roomIndex=3',{waitUntil:'networkidle2',timeout:90000});
await new Promise(r=>setTimeout(r,8000));
await p.reload({waitUntil:'networkidle2',timeout:90000});
await new Promise(r=>setTimeout(r,22000));
console.log('  hud:', (await p.evaluate(()=>document.getElementById('hud').innerText)).replace(/\n/g,' | '));
const err = await p.evaluate(()=>document.getElementById('err').textContent);
if (err) console.log('  PAGE ERROR:', err.slice(0,300));
console.log('  scene objects:', await p.evaluate(()=>window.__n ?? 'n/a'));
console.log('  console errors:', errs.length); errs.slice(0,4).forEach(e=>console.log('    '+e.slice(0,140)));
await p.screenshot({path:'/tmp/wing3d.png'});
await b.close();
