// GENERATED by scripts/generate-clip-timing.mjs — re-run after changing clips.
//
// Per-clip combat timing. `impact` is the frame of greatest motion, i.e. when
// the blow lands; `useful` is start-to-impact plus a short follow-through.
// The renderer plays only the useful portion and blends out the settle, so a
// three-second performance can occupy a 1.5s GCD at natural speed instead of
// being fast-forwarded into it.
export const CLIP_TIMING = {
  "alert": {
    "duration": 4.033,
    "start": 0.067,
    "impact": 3.667,
    "useful": 3.85
  },
  "angry_stomp": {
    "duration": 8.033,
    "start": 0.067,
    "impact": 1.1,
    "useful": 1.283
  },
  "attack": {
    "duration": 2.833,
    "start": 0.067,
    "impact": 1.067,
    "useful": 1.25
  },
  "axe_spin_attack": {
    "duration": 2.533,
    "start": 0.067,
    "impact": 2.033,
    "useful": 2.217
  },
  "axe_stance": {
    "duration": 6.133,
    "start": 0.7,
    "impact": 3.167,
    "useful": 2.717
  },
  "backflip": {
    "duration": 2.167,
    "start": 0.067,
    "impact": 0.867,
    "useful": 1.05
  },
  "basic_jump": {
    "duration": 5.933,
    "start": 1.4,
    "impact": 2.4,
    "useful": 1.25
  },
  "battle_pose": {
    "duration": 4.033,
    "start": 0.067,
    "impact": 1.933,
    "useful": 2.117
  },
  "block": {
    "duration": 3.5,
    "start": 0.133,
    "impact": 1.033,
    "useful": 1.15
  },
  "block_2": {
    "duration": 1.633,
    "start": 0.067,
    "impact": 0.3,
    "useful": 0.483
  },
  "block_3": {
    "duration": 1.533,
    "start": 0.2,
    "impact": 0.533,
    "useful": 0.583
  },
  "block_4": {
    "duration": 1.567,
    "start": 0.067,
    "impact": 1.333,
    "useful": 1.5
  },
  "block_5": {
    "duration": 2.567,
    "start": 0.1,
    "impact": 0.533,
    "useful": 0.683
  },
  "charged_axe_chop": {
    "duration": 7.7,
    "start": 1.567,
    "impact": 2.533,
    "useful": 1.217
  },
  "charged_ground_slam": {
    "duration": 3.033,
    "start": 0.067,
    "impact": 1.633,
    "useful": 1.817
  },
  "charged_slash": {
    "duration": 2.267,
    "start": 0.067,
    "impact": 0.2,
    "useful": 0.383
  },
  "charged_spell_cast": {
    "duration": 2.7,
    "start": 0.067,
    "impact": 0.467,
    "useful": 0.65
  },
  "charged_upward_slash": {
    "duration": 3.233,
    "start": 0.1,
    "impact": 0.967,
    "useful": 1.117
  },
  "combat_stance": {
    "duration": 1.7,
    "start": 0.233,
    "impact": 0.7,
    "useful": 0.717
  },
  "counterstrike": {
    "duration": 6.533,
    "start": 0.067,
    "impact": 5.633,
    "useful": 5.817
  },
  "dead": {
    "duration": 3,
    "start": 0.067,
    "impact": 0.067,
    "useful": 0.25
  },
  "dodge_and_counter": {
    "duration": 9.367,
    "start": 0.067,
    "impact": 4.7,
    "useful": 4.883
  },
  "double_blade_spin": {
    "duration": 5.7,
    "start": 0.067,
    "impact": 1.633,
    "useful": 1.817
  },
  "double_combo_attack": {
    "duration": 2.867,
    "start": 0.067,
    "impact": 1.3,
    "useful": 1.483
  },
  "dying_backwards": {
    "duration": 2.267,
    "start": 0.367,
    "impact": 1.333,
    "useful": 1.217
  },
  "heavy_hammer_swing": {
    "duration": 1.867,
    "start": 0.067,
    "impact": 1.433,
    "useful": 1.617
  },
  "hit_reaction": {
    "duration": 5.633,
    "start": 0.4,
    "impact": 1.667,
    "useful": 1.517
  },
  "hit_reaction_1": {
    "duration": 1.667,
    "start": 0.067,
    "impact": 0.6,
    "useful": 0.783
  },
  "idle": {
    "duration": 4.033,
    "start": 0.633,
    "impact": 2.067,
    "useful": 1.683
  },
  "idle_03": {
    "duration": 5.367,
    "start": 0.067,
    "impact": 0.067,
    "useful": 0.25
  },
  "injured_walk": {
    "duration": 8.7,
    "start": 0.067,
    "impact": 5.5,
    "useful": 5.683
  },
  "lean_forward_sprint": {
    "duration": 0.633,
    "start": 0.067,
    "impact": 0.267,
    "useful": 0.45
  },
  "left_slash": {
    "duration": 3.2,
    "start": 0.2,
    "impact": 0.6,
    "useful": 0.65
  },
  "mage_spell_cast": {
    "duration": 4.333,
    "start": 0.233,
    "impact": 0.933,
    "useful": 0.95
  },
  "mage_spell_cast_2": {
    "duration": 3.033,
    "start": 0.067,
    "impact": 1.067,
    "useful": 1.25
  },
  "mage_spell_cast_3": {
    "duration": 3.567,
    "start": 0.167,
    "impact": 1.467,
    "useful": 1.55
  },
  "mage_spell_cast_4": {
    "duration": 2.267,
    "start": 0.067,
    "impact": 0.233,
    "useful": 0.417
  },
  "mage_spell_cast_6": {
    "duration": 2.333,
    "start": 0.067,
    "impact": 0.667,
    "useful": 0.85
  },
  "mage_spell_cast_8": {
    "duration": 1.4,
    "start": 0.067,
    "impact": 0.2,
    "useful": 0.383
  },
  "punch_combo": {
    "duration": 2.5,
    "start": 0.267,
    "impact": 0.633,
    "useful": 0.617
  },
  "quick_step_spin_dodge": {
    "duration": 1.233,
    "start": 0.067,
    "impact": 0.4,
    "useful": 0.583
  },
  "reaping_swing": {
    "duration": 5.967,
    "start": 0.4,
    "impact": 4.167,
    "useful": 4.017
  },
  "right_hand_sword_slash": {
    "duration": 1.533,
    "start": 0.167,
    "impact": 0.433,
    "useful": 0.517
  },
  "rightward_spin": {
    "duration": 8.033,
    "start": 0.067,
    "impact": 0.367,
    "useful": 0.55
  },
  "roll_dodge": {
    "duration": 1.3,
    "start": 0.233,
    "impact": 0.5,
    "useful": 0.517
  },
  "roll_dodge_1": {
    "duration": 1.3,
    "start": 0.067,
    "impact": 0.767,
    "useful": 0.95
  },
  "roll_dodge_2": {
    "duration": 2.067,
    "start": 0.067,
    "impact": 0.333,
    "useful": 0.517
  },
  "run": {
    "duration": 0.767,
    "start": 0.067,
    "impact": 0.5,
    "useful": 0.683
  },
  "run_03": {
    "duration": 0.833,
    "start": 0.067,
    "impact": 0.1,
    "useful": 0.283
  },
  "run_and_shoot": {
    "duration": 0.7,
    "start": 0.067,
    "impact": 0.333,
    "useful": 0.517
  },
  "run_fast": {
    "duration": 0.5,
    "start": 0.067,
    "impact": 0.167,
    "useful": 0.35
  },
  "shield_push": {
    "duration": 2.433,
    "start": 0.267,
    "impact": 1.1,
    "useful": 1.083
  },
  "skill_01": {
    "duration": 1.1,
    "start": 0.067,
    "impact": 0.267,
    "useful": 0.45
  },
  "skill_02": {
    "duration": 1.333,
    "start": 0.033,
    "impact": 0.267,
    "useful": 0.483
  },
  "skill_03": {
    "duration": 1.667,
    "start": 0.067,
    "impact": 0.767,
    "useful": 0.95
  },
  "sprint_roll_and_flip": {
    "duration": 2.8,
    "start": 0.067,
    "impact": 0.633,
    "useful": 0.817
  },
  "stand_dodge": {
    "duration": 1.467,
    "start": 0.1,
    "impact": 0.533,
    "useful": 0.683
  },
  "standard_forward_charge": {
    "duration": 0.667,
    "start": 0.067,
    "impact": 0.3,
    "useful": 0.483
  },
  "sword_judgment": {
    "duration": 4.4,
    "start": 0.1,
    "impact": 0.633,
    "useful": 0.783
  },
  "sword_parry": {
    "duration": 1.9,
    "start": 0.067,
    "impact": 0.3,
    "useful": 0.483
  },
  "sword_parry_backward": {
    "duration": 1.4,
    "start": 0.1,
    "impact": 0.733,
    "useful": 0.883
  },
  "sword_shout": {
    "duration": 6.2,
    "start": 0.267,
    "impact": 3.3,
    "useful": 3.283
  },
  "thrust_slash": {
    "duration": 3.033,
    "start": 0.067,
    "impact": 2.433,
    "useful": 2.617
  },
  "two_handed_parry": {
    "duration": 1.4,
    "start": 0.067,
    "impact": 0.2,
    "useful": 0.383
  },
  "victory_cheer": {
    "duration": 9.367,
    "start": 0.067,
    "impact": 3.567,
    "useful": 3.75
  },
  "victory_fist_pump": {
    "duration": 1.567,
    "start": 0.067,
    "impact": 0.433,
    "useful": 0.617
  },
  "walk_backward": {
    "duration": 0.933,
    "start": 0.067,
    "impact": 0.567,
    "useful": 0.75
  },
  "walk_fight_back": {
    "duration": 1.767,
    "start": 0.067,
    "impact": 1.733,
    "useful": 1.7
  },
  "walk_fight_forward": {
    "duration": 1.767,
    "start": 0.067,
    "impact": 0.7,
    "useful": 0.883
  },
  "weapon_combo": {
    "duration": 3.7,
    "start": 0.067,
    "impact": 0.833,
    "useful": 1.017
  },
  "weapon_combo_1": {
    "duration": 3.567,
    "start": 0.067,
    "impact": 2.467,
    "useful": 2.65
  },
  "weapon_combo_2": {
    "duration": 4.567,
    "start": 0.067,
    "impact": 2.7,
    "useful": 2.883
  }
};

/** Timing for a clip, or null when it has none (renderer uses whole-clip). */
export function clipTiming(name) {
  return CLIP_TIMING[name] ?? null;
}
