// GENERATED by scripts/bootstrap-dungeon-manifest.mjs — re-run to refresh.
//
// Single source of truth for dungeon content. The engine derives its placement
// pools from PROPS rather than hardcoding a dozen separate arrays, and themes
// resolve their textures through TEXTURES. Declaring an asset here is what makes
// it both generated and consumed, which is what stops the two sides drifting.
//
// placement: wall | corner | center | scatter | cluster | ring | pillar | rubble
//            | arch | hanging | special      — placeable today
//            | blocked:<system>              — asset is fine, no system places it
//            | unclassified                  — needs a decision
// A prop may carry several placements; poolFor() matches any of them.
//
// Run `npm run content:check` after editing.

export const PROPS = [
  { id: 'arch_keystone', placements: ['arch'] },
  { id: 'gate_archway', placements: ['blocked:architecture'] },
  { id: 'runic_door_sealed', placements: ['blocked:architecture'] },
  { id: 'stairs_ascending', placements: ['blocked:architecture'] },
  { id: 'stairs_descending', placements: ['blocked:architecture'] },
  { id: 'stone_bridge', placements: ['blocked:architecture'] },
  { id: 'fire_vent', placements: ['blocked:hazard'] },
  { id: 'pressure_plate', placements: ['blocked:hazard'] },
  { id: 'spike_trap', placements: ['blocked:hazard'] },
  { id: 'swinging_blade', placements: ['blocked:hazard'] },
  { id: 'altar_runic', placements: ['center'] },
  { id: 'blood_altar', placements: ['center'] },
  { id: 'blood_pool', placements: ['center'] },
  { id: 'destructible_pillar', placements: ['center'] },
  { id: 'ember_pool', placements: ['center'] },
  { id: 'lever_pillar', placements: ['center'] },
  { id: 'ossuary_bone_throne', placements: ['center'] },
  { id: 'ritual_circle', placements: ['center'] },
  { id: 'ritual_circle_large', placements: ['center'] },
  { id: 'ritual_demon_statue', placements: ['center'] },
  { id: 'sacrificial_pedestal', placements: ['center'] },
  { id: 'skull_pyramid', placements: ['center'] },
  { id: 'stone_altar', placements: ['center'] },
  { id: 'throne_dais', placements: ['center'] },
  { id: 'throne_massive', placements: ['center'] },
  { id: 'skull_idol', placements: ['cluster'] },
  { id: 'broken_pillar', placements: ['corner', 'center', 'ring', 'pillar'] },
  { id: 'buttress', placements: ['corner', 'ring'] },
  { id: 'pillar_crumbling', placements: ['corner', 'center', 'ring', 'pillar'] },
  { id: 'pillar_intact', placements: ['corner', 'center', 'pillar'] },
  { id: 'rune_pillar', placements: ['corner', 'center', 'pillar'] },
  { id: 'collapsed_archway', placements: ['ring', 'arch'] },
  { id: 'ash_pile', placements: ['scatter', 'cluster'], destructible: true },
  { id: 'bone_pile', placements: ['scatter', 'cluster'], destructible: true },
  { id: 'burial_urn', placements: ['scatter', 'cluster'], destructible: true },
  { id: 'rubble_pile', placements: ['scatter', 'cluster', 'rubble'] },
  { id: 'rubble_small', placements: ['scatter', 'cluster', 'rubble'], destructible: true },
  { id: 'scattered_books', placements: ['scatter'] },
  { id: 'shield_broken', placements: ['scatter'] },
  { id: 'skeletal_remains_clutching', placements: ['scatter'] },
  { id: 'skull_stack', placements: ['scatter', 'cluster'], destructible: true },
  { id: 'treasure_pile', placements: ['scatter'] },
  { id: 'ancient_idol', placements: ['special'] },
  { id: 'brazier', placements: ['special'] },
  { id: 'cursed_bell', placements: ['special'] },
  { id: 'doorway_archway_runic', placements: ['special'] },
  { id: 'merchant_crucible', placements: ['special'] },
  { id: 'puzzle_obelisk', placements: ['special'] },
  { id: 'treasure_chest_locked', placements: ['special'] },
  { id: 'boss_banner_large', placements: ['wall'] },
  { id: 'brazier_ornate_boss', placements: ['wall'] },
  { id: 'broken_statue', placements: ['wall', 'ring'] },
  { id: 'candelabrum_tall', placements: ['wall'] },
  { id: 'crypt_door_sealed', placements: ['wall'] },
  { id: 'fallen_banner', placements: ['wall'], cloth: true },
  { id: 'family_banner_purple', placements: ['wall'] },
  { id: 'family_banner_red', placements: ['wall'] },
  { id: 'guardian_statue', placements: ['wall', 'ring'] },
  { id: 'guardian_statue_kneeling', placements: ['wall'] },
  { id: 'guardian_statue_standing', placements: ['wall'] },
  { id: 'guardian_statue_warding', placements: ['wall'] },
  { id: 'hanging_cage', placements: ['wall'] },
  { id: 'hanging_cage_skeleton', placements: ['wall'] },
  { id: 'hanging_lantern', placements: ['wall'] },
  { id: 'iron_brazier_tall', placements: ['wall'] },
  { id: 'iron_chains', placements: ['wall'], cloth: true },
  { id: 'iron_door_barred', placements: ['wall'] },
  { id: 'iron_gate_closed', placements: ['wall'] },
  { id: 'iron_gate_open', placements: ['wall'] },
  { id: 'ossuary_skull_arch', placements: ['wall'] },
  { id: 'pew_broken', placements: ['wall'] },
  { id: 'prayer_pew', placements: ['wall'] },
  { id: 'ritual_brazier_lit', placements: ['wall'] },
  { id: 'ritual_chains_dangling', placements: ['wall'] },
  { id: 'rusted_armor_pile', placements: ['wall'] },
  { id: 'sarcophagus', placements: ['wall'] },
  { id: 'skeletal_remains_seated', placements: ['wall'] },
  { id: 'skull_chandelier', placements: ['wall'] },
  { id: 'stained_glass_window', placements: ['wall'] },
  { id: 'supply_crate', placements: ['wall'] },
  { id: 'training_dummy_decayed', placements: ['wall'] },
  { id: 'wall_torch_iron', placements: ['wall'] },
  { id: 'weapon_axe_in_dummy', placements: ['wall'] },
  { id: 'weapon_sword_in_stone', placements: ['wall'] },
  { id: 'web_cocoon', placements: ['wall'] },
  { id: 'wooden_barrel_cracked', placements: ['wall'] },
];

export const TEXTURES = [
  { id: 'ceiling_beams', role: 'ceiling', themes: [] },
  { id: 'ceiling_dark_vault', role: 'ceiling', themes: [] },
  { id: 'ceiling_open_sky', role: 'ceiling', themes: [] },
  { id: 'ceiling_vault', role: 'ceiling', themes: [] },
  { id: 'ceiling_vaulted', role: 'ceiling', themes: [] },
  { id: 'decal_blood_handprint', role: 'decal', themes: [] },
  { id: 'decal_blood_runes', role: 'decal', themes: [] },
  { id: 'decal_blood_splatter', role: 'decal', themes: [] },
  { id: 'decal_burn_scorch', role: 'decal', themes: [] },
  { id: 'decal_claw_marks', role: 'decal', themes: [] },
  { id: 'decal_frost_patch', role: 'decal', themes: [] },
  { id: 'decal_holy_circle', role: 'decal', themes: [] },
  { id: 'decal_holy_seal', role: 'decal', themes: [] },
  { id: 'decal_skull_glyph', role: 'decal', themes: [] },
  { id: 'decal_summoning_circle', role: 'decal', themes: [] },
  { id: 'floor_ashen', role: 'floor', themes: ['crucible_below', 'ashfall_dunes'] },
  { id: 'floor_blood', role: 'floor', themes: ['bloodspire_keep'] },
  { id: 'floor_blood_marsh', role: 'floor', themes: ['bloodspire_keep'] },
  { id: 'floor_blood_soaked', role: 'floor', themes: ['crucible_below', 'bloodspire_keep'] },
  { id: 'floor_bone_dust', role: 'floor', themes: ['crucible_below', 'frostbite_caverns'] },
  { id: 'floor_chapel', role: 'floor', themes: [] },
  { id: 'floor_cracked', role: 'floor', themes: ['crucible_below', 'frostbite_caverns', 'verdant_ruins', 'ashfall_dunes'] },
  { id: 'floor_crypt', role: 'floor', themes: [] },
  { id: 'floor_iron_grate', role: 'floor', themes: [] },
  { id: 'floor_marble_inlay', role: 'floor', themes: [] },
  { id: 'floor_moss_overgrown', role: 'floor', themes: ['verdant_ruins'] },
  { id: 'floor_obsidian_polished', role: 'floor', themes: [] },
  { id: 'floor_ritual', role: 'floor', themes: ['bloodspire_keep'] },
  { id: 'floor_runic', role: 'floor', themes: ['crucible_below'] },
  { id: 'floor_runic_glowing', role: 'floor', themes: [] },
  { id: 'floor_sand_dune', role: 'floor', themes: ['ashfall_dunes'] },
  { id: 'floor_snow_packed', role: 'floor', themes: ['frostbite_caverns'] },
  { id: 'floor_stone', role: 'floor', themes: ['crucible_below', 'verdant_ruins', 'ashfall_dunes'] },
  { id: 'archway_stone', role: 'misc', themes: [] },
  { id: 'banner_demonic', role: 'misc', themes: [] },
  { id: 'banner_holy', role: 'misc', themes: [] },
  { id: 'banner_purple', role: 'misc', themes: [] },
  { id: 'banner_red', role: 'misc', themes: [] },
  { id: 'cloth_banner', role: 'misc', themes: [] },
  { id: 'door_iron', role: 'misc', themes: [] },
  { id: 'fog_volumetric', role: 'misc', themes: [] },
  { id: 'metal_iron', role: 'misc', themes: [] },
  { id: 'splash_crucible_below', role: 'misc', themes: [] },
  { id: 'tex_heightmap_rubble', role: 'misc', themes: [] },
  { id: 'tex_heightmap_stone', role: 'misc', themes: [] },
  { id: 'vfx_godray', role: 'misc', themes: [] },
  { id: 'void_skybox', role: 'misc', themes: [] },
  { id: 'wall_blackened', role: 'wall', themes: [] },
  { id: 'wall_bloodied', role: 'wall', themes: ['bloodspire_keep'] },
  { id: 'wall_bone', role: 'wall', themes: [] },
  { id: 'wall_broken_relief', role: 'wall', themes: ['crucible_below'] },
  { id: 'wall_carved', role: 'wall', themes: ['bloodspire_keep'] },
  { id: 'wall_chapel', role: 'wall', themes: [] },
  { id: 'wall_charred', role: 'wall', themes: ['bloodspire_keep'] },
  { id: 'wall_columned', role: 'wall', themes: [] },
  { id: 'wall_cracked', role: 'wall', themes: [] },
  { id: 'wall_crypt', role: 'wall', themes: [] },
  { id: 'wall_ice_glacial', role: 'wall', themes: ['frostbite_caverns'] },
  { id: 'wall_iron_clad', role: 'wall', themes: [] },
  { id: 'wall_mossy', role: 'wall', themes: ['verdant_ruins'] },
  { id: 'wall_obsidian', role: 'wall', themes: [] },
  { id: 'wall_ornate_panel', role: 'wall', themes: ['crucible_below'] },
  { id: 'wall_overgrown', role: 'wall', themes: [] },
  { id: 'wall_runic', role: 'wall', themes: ['ashfall_dunes'] },
  { id: 'wall_runic_glow', role: 'wall', themes: ['crucible_below', 'frostbite_caverns', 'bloodspire_keep'] },
  { id: 'wall_sandstone_carved', role: 'wall', themes: ['ashfall_dunes'] },
  { id: 'wall_stained_glass', role: 'wall', themes: [] },
  { id: 'wall_stone', role: 'wall', themes: ['crucible_below', 'frostbite_caverns', 'verdant_ruins', 'ashfall_dunes'] },
  { id: 'wall_torchlit', role: 'wall', themes: [] },
  { id: 'wall_vine_overgrown', role: 'wall', themes: ['verdant_ruins'] },
];

/** Prop ids for a placement pool, excluding anything blocked or unclassified. */
export function poolFor(placement) {
  return PROPS.filter(p => p.placements.includes(placement)).map(p => p.id);
}

export const DESTRUCTIBLE = PROPS.filter(p => p.destructible).map(p => p.id);
export const CLOTH = PROPS.filter(p => p.cloth).map(p => p.id);

/** Textures a theme declares for a role, most specific first. */
export function themeTexture(themeId, role) {
  const t = TEXTURES.find(x => x.role === role && x.themes.includes(themeId));
  return t ? t.id : null;
}

export const BLOCKED = PROPS
  .filter(p => p.placements.some(x => x.startsWith('blocked:')))
  .map(p => ({ id: p.id, system: p.placements.find(x => x.startsWith('blocked:')).split(':')[1] }));
